http_port 172.29.0.1:3128

acl console_agents src 172.29.0.0/24
acl CONNECT method CONNECT
acl SSL_ports port 443
acl approved_destinations dstdomain yufan-data-lake.s3.ap-southeast-1.amazonaws.com
acl approved_destinations dstdomain yufan-data-lake.s3.amazonaws.com

acl forbidden_destinations dst 0.0.0.0/8
acl forbidden_destinations dst 10.0.0.0/8
acl forbidden_destinations dst 100.64.0.0/10
acl forbidden_destinations dst 127.0.0.0/8
acl forbidden_destinations dst 169.254.0.0/16
acl forbidden_destinations dst 172.16.0.0/12
acl forbidden_destinations dst 192.168.0.0/16
acl forbidden_destinations dst 224.0.0.0/4
acl forbidden_destinations dst 240.0.0.0/4

http_access deny forbidden_destinations
http_access deny !SSL_ports
http_access allow console_agents CONNECT SSL_ports approved_destinations
http_access deny all

cache deny all
access_log none
cache_store_log none
forwarded_for delete
via off
dns_v4_first on
