from __future__ import annotations

__all__ = [
    "BLOCK_CANDIDATE_PACKET_INVALID",
    "BLOCK_CAPABILITY_INVENTORY_MISSING",
    "BLOCK_CHEAP_SCREEN_FORMAL_PROMOTION_FORBIDDEN",
    "BLOCK_DATA_DEPENDENCY_UNRESOLVED",
    "BLOCK_OUTPUT_OUTSIDE_WORKSPACE",
    "BLOCK_TEMPLATE_REGISTRY_INVALID",
    "BLOCK_WORKSPACE_MISSING",
]

BLOCK_WORKSPACE_MISSING = "BLOCK_FACTORFORGE_MINER_WORKSPACE_MISSING"
BLOCK_TEMPLATE_REGISTRY_INVALID = "BLOCK_FACTORFORGE_MINER_TEMPLATE_REGISTRY_INVALID"
BLOCK_CANDIDATE_PACKET_INVALID = "BLOCK_FACTORFORGE_MINER_CANDIDATE_PACKET_INVALID"
BLOCK_CAPABILITY_INVENTORY_MISSING = "BLOCK_FACTORFORGE_MINER_CAPABILITY_INVENTORY_MISSING"
BLOCK_CHEAP_SCREEN_FORMAL_PROMOTION_FORBIDDEN = "BLOCK_FACTORFORGE_MINER_CHEAP_SCREEN_FORMAL_PROMOTION_FORBIDDEN"
BLOCK_DATA_DEPENDENCY_UNRESOLVED = "BLOCK_FACTORFORGE_MINER_DATA_DEPENDENCY_UNRESOLVED"
BLOCK_OUTPUT_OUTSIDE_WORKSPACE = "BLOCK_FACTORFORGE_MINER_OUTPUT_OUTSIDE_WORKSPACE"
